### ISSUE TITLE
color参数

### ISSUE THREAD

**Issue by kaywer** [zhaipro/unet#2]
请问color里面的三个数字分别代表什么？我尝试设置rgb值，没能达到预期效果。

**Comment by zhaipro** [comment]
@kaywer 贴个例子给我，参数和效果。

**Comment by kaywer** [comment]
@zhaipro 我将color改成(220, 20, 60)，期望结果是红色，但染成了蓝色。

![image](https://user-images.githubusercontent.com/24730324/63430376-03fec700-c44f-11e9-85e0-35ee5be3732a.png)

**Comment by zhaipro** [comment]
处理图片用的是opencv，在它的眼里颜色是BGR格式。

**Comment by kaywer** [comment]
可以了，效果很好，赞！
